name: Install Docker on Server

on:
  workflow_dispatch:
    inputs:
      ip:
        description: "目标服务器 IP"
        required: true
        type: string

jobs:
  install-docker:
    runs-on: ubuntu-latest
    steps:
      - name: 远程安装 Docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ github.event.inputs.ip }}
          username: root
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            # 更新系统
            apt update
            apt install -y ca-certificates curl gnupg lsb-release

            # 添加 Docker 官方 GPG 密钥
            mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

            # 添加 Docker 仓库
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
              | tee /etc/apt/sources.list.d/docker.list > /dev/null

            # 安装 Docker
            apt update
            apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

            # 验证安装
            docker --version
