name: ssh deploy

on:
  workflow_dispatch:
    inputs:
      ip:
        description: "目标服务器 IP"
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 打包当前仓库
        run: tar -czf repo.tar.gz ./*

      - name: 上传文件
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ github.event.inputs.ip }}
          username: root
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          source: "repo.tar.gz"
          target: "~/"

      - name: 远程解压并启动容器
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ github.event.inputs.ip }}
          username: root
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
             git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/alaric8888/customer-service.git
             